@ECHO OFF
SETLOCAL

SET PROG_ZANDRONUM="%DOOMDIR%\Zandronum\zandronum.EXE"
SET ZANFLAGSVALUE=""

IF DEFINED ZANFLAGS (
    SET ZANFLAGS_VALUE=%ZANFLAGS%
)

CALL %PROG_ZANDRONUM% -file "%CD%/PK7_Source" -host %ZANFLAGS_VALUE% %*